### ISSUE TITLE
AUR package popularity percentage calculation issues

### ISSUE THREAD

**Issue by milkmiruku** [trizen/trizen#109]
![silver_2018-02-07-22 04 02](https://user-images.githubusercontent.com/108225/35944161-69dc8838-0c53-11e8-936e-f2546c75822a.png)

Returned values are weird. Some are reordered. At least Ardour is missing.

[AUR search link](https://aur.archlinux.org/packages/?O=0&K=sequencer&SB=p&SO=a)

**Comment by trizen** [comment]
`ardour-git` is not included in the RPC results when searching for "sequencer" because it does not contain the keyword "sequencer" in the name or in the description of the package.

See: https://aur.archlinux.org/rpc.php?v=5&type=search&arg=sequencer

It does, however, include the "sequencer" keyword in the AUR keywords. (see https://aur.archlinux.org/packages/ardour-git/), but for now, there is no option for searching by AUR keywords. (see: https://wiki.archlinux.org/index.php/AurJson#search)

The reordering has been fixed [here](https://github.com/trizen/trizen/commit/2b530c759682f4fab49d6ba0d65d3a72ff025a71). Thanks for reporting the issue.

**Comment by milkmiruku** [comment]
searching for colormake gives;
```
2 aur/colormake-git r33.05688ab-1 [1+] [6e-05%] [4 Dec 2015]
    A simple wrapper around make to make it's output more readable
1 aur/colormake 0.9-2 [installed] [7+] [0.12%] [22 Feb 2017]
    A simple wrapper around make to make it's output more readable.
```
