### ISSUE TITLE
add noconfirm config file setting

### ISSUE THREAD

**Issue by deathtrip** [trizen/trizen#119]
Please add a noconfirm config file option, so that people who like to have automated installing don't have to type it before every install.

**Comment by mbloms** [comment]
There's a reason this isn't on by default. I don't think this behaviour should be encouraged.

**Comment by deathtrip** [comment]
I'm not asking for it to be on by default, i just want the option to enable it.

**Comment by mbloms** [comment]
Yes, and I'm saying why I don't think that would be a good feature. It's unsafe, and you should not be able to make running unknown code the normal behavior. It will be abused.

**Comment by trizen** [comment]
@deathtrip adding a `noconfirm` config-option is trivial. But is it good? Not really, because it does not allow the user to resolve conflicting packages.

An equally bad config-option already available (called `install_built_with_noconfirm` - submitted as a pull request: https://github.com/trizen/trizen/pull/27/commits/7e12ecda93ec52de3d9845f14c528edbce82f134) installs built packages with the `--noconfirm` pacman option, which, again, will not ask about conflicting packages.

Another config-option, highly not recommended to be set to a true value, is `noedit`, which will build everything without prompting the user to inspect and/or edit the build files of a package.

By setting `install_built_with_noconfirm` and `noedit` to `1`, you get a version of `--noconfirm`, which builds and installs everything without asking any questions, but asks questions in other contexts, such as during `-Syu` or during `-Scc`.

Alternatively, if you insist in using `trizen` as a truly non-interactive program, consider creating a local alias:

```bash
trizen="trizen --noconfirm $@"
```
