### ISSUE TITLE
Use correct build order for rebuilds

### ISSUE THREAD

**Issue by Skycoder42** [trizen/trizen#124]
When rebuilding already installed packages (for example because a library they depend on got updated) some dependencies are not built in the order they would be when installing.

Example: Package A and B are AUR packages, package C is an official package. A depends on B, and B depends on C. If I run `trizen -S A B` it is possible that first A and then B are built and installed. The expected order would be first B, then A, as for a normal install.

**Comment by trizen** [comment]
> The expected order would be first B, then A, as for a normal install.

Since the dependency `B` is already installed and up-to-date, it is considered "resolved". It will only be updated first if the PKGBUILD of `A` specifies that it wants a higher version of the dependency `B` than the one that is already installed.

See also: https://github.com/trizen/trizen/issues/121

**Comment by Skycoder42** [comment]
Is there any way to enforce that behaviour (Some CLI switch?) As for my example trizen would fail because B is broken thanks to the update to C and thus A cannot be built. I know I can either run trizen twice or modify B to make it an update, but I would prefer this to work automatically.
