### ISSUE TITLE
`clone_dir` is not configurable in `$config_file`

### ISSUE THREAD

**Issue by monotykamary** [trizen/trizen#17]
`trizen --update-config` will cleanly dump `clone_dir => "/tmp/trizen-$USER"` and all relevant `$config` variables in `$HOME/.config/trizen.conf`.

However, editing the directory for `clone_dir` in the config file will not change the clone directory on a fresh `trizen -S $pkgname` run as it will default to the `/tmp/trizen-$USER` directory defined in `$lconfig{clone_dir} = ($CONFIG{clone_dir} //= catdir(tmpdir(), "$execname-$user"));`

---

`trizen --clone_dir=/home/tom/.cache/trizen -S $pkgname` works as intended.

`trizen --clone_dir=/home/tom/.cache/trizen -Rcn $pkgname` will return `/usr/bin/pacman: unrecognized option '--clone_dir=/home/tom/.cache/trizen'`. If this is intended to avoid the latter error, feel free to close this issue.

**Comment by monotykamary** [comment]
Issue has indeed been resolved in commit [da3560ae](https://github.com/trizen/trizen/commit/da3560e2f70af73ca0440f35688e10e95e53320b). Thank you for all your efforts!

**Comment by trizen** [comment]
Thank you for reporting this issue. It was successfully fixed [here](https://github.com/trizen/trizen/commit/da3560e2f70af73ca0440f35688e10e95e53320b).

Regarding the second part of the issue, `--clone-dir` (and other trizen-specific arguments) were passed to pacman by accident. This issue was fixed [here](https://github.com/trizen/trizen/commit/e96f257b2bc9389a09de5d20b72e7ccb8ebac8a5).
