### ISSUE TITLE
Does trizen support regex?

### ISSUE THREAD

**Issue by gusbemacbe** [trizen/trizen#205]
Merhaba ve iyi akşamlar @trizen,

I would like to install or search multiples applications, using regex, like pacman does, for example:

```zsh
trizen -Ss "{aic94xx|wd719x}"
trizen -Ss "texlive-{fonts|music}"
trizen -Ss aic94xx wd719x
trizen -Si "{aic94xx|wd719x}"
trizen -Si "texlive-{fonts|music}"
trizen -Si aic94xx wd719x
```

Teşekkür ederim for your attention, help, patience and understanding!

**Comment by trizen** [comment]
Hello @gusbemacbe,

Yes, it's possible to search by a regex, but only in pacman's repos and in locally installed packages.

Example:

```console
$ trizen -Ssr "ge[ab].y"
```

Output:

```
community/geany 1.35.0-1
    Fast and lightweight IDE
community/geany-plugins 1.35-1
    Plugins for Geany
community/geary 1:3.32.1-1
    A lightweight email client for the GNOME desktop
```

Since [AUR RPC](https://wiki.archlinux.org/index.php/Aurweb_RPC_interface) does not provide support for searching by a regex, trizen cannot provide this feature either.

In AUR, it's possible to search using literal keywords, then filter the results using `grep`, `egrep`, `ack`, etc...

Example:

```console
$ trizen --forcecolors -Ss perl-math | ack "math-(big|any)" 
```

Output:

```
aur/perl-math-anynum 0.32-1 [1+] [0.00%] [8 Jun 2019]
aur/perl-math-bigint 1.999816-1 [0+] [0.00%] [27 Oct 2018]
aur/perl-math-bigint-gmp 1.6006-1 [10+] [0.00%] [13 Oct 2018]
aur/perl-math-bigint-lite 0.18-1 [0+] [0.00%] [4 Sep 2018]
```

Hopefully this answers your question.
