### ISSUE TITLE
Pacman long options

### ISSUE THREAD

**Issue by notramo** [trizen/trizen#21]
What about adding support for pacman long options?
This command tries to install the package instead of search for it (because '--search' is not supported by trizen, and it ignores it):
```trizen -S --search <package name>```
It gives a warning:
```[!] Invalid option <<--search>>```

I have two ideas to solve this issue:

- Trizen should give all unsupported options (e. g. '--search') to pacman, and if an option isn't supported by pacman, it exits.
- Make an array, that contains the long pacman options, that are not supported by trizen (adding them to %lconfig not needed), but pacman understands them.

**Comment by trizen** [comment]
Thanks for the suggestion. Experimental support for long arguments has been added in the above commit.

**Comment by notramo** [comment]
Cool.

**Comment by archderwelt** [comment]
Sorry for reopening this; I have a similar issue to this one and that's why am commenting here. Just in case it is not wanted, I would open a new issue :-)    
I have a similar Issue, where a long argument is required for my use case and I would be happy If you could add it. The argument is `--cachedir=/path/to/dir/`. I need this since I usually save packages to external drive (small SSD :( ).    
Thank you and happy new year by the way :)
