### ISSUE TITLE
Dependency Resolution Issue of Split Versioned Packages

### ISSUE THREAD

**Issue by greghab** [trizen/trizen#219]
Trizen cannot install packages like Gazebo (https://aur.archlinux.org/packages/gazebo/), which have dependencies like `sdformat=6`. the package sdformat is at version 8 (`sdformat | 8.2.0-0`). Trizen looks for a version 6 of this package, however it does not exists, and thus it can't find the dependency. However, there is a separate package with that specific version, `sdformat-6 | 6.2.0-3`. 

Note, if you edit the pkgbuild to specify `sdformat-6`, instead of `sdformat=6`, it installs fine.
`yay` can handle this depedency resolution without modification.

The following packages have this issue: `sdformat-6 ignition-math-4 ignition-transport-4 ignition-common-1 ignition-fuel_tools-1 ignition-msgs-1 ignition-cmake-0`. I guess one potential fix, is if it asks for a whole number version of a package, add a dash and the whole number to the end of the package name, and install that. I'm sure yay is doing something much more intelligent though.

**Comment by trizen** [comment]
The equal sign in `depname=version` specifies an exact version restriction. If the `gazebo` package does not really require version `6` of `sdformat`, then it should specify `sdformat>=6`. Or if it requires `sdformat-6` instead, then the PKGBUILD should reflect that.

Trizen does the right thing here.

See also: https://wiki.archlinux.org/index.php/PKGBUILD#depends

**Comment by greghab** [comment]
I get what you're saying, but the pkgbuild for example contains only `sdformat=6`, yet the on the aur page for the package it states `sdformat=6 (libsdformat-hg, sdformat-6)`.

I.E., the AUR webpage (https://aur.archlinux.org/packages/gazebo/)  correctly finds and displays the dependency of `sdformat-6` just from the  `sdformat=6` input, leading me to believe  `sdformat=6` is correct syntax.

Unless I'm misunderstanding how the AUR website works.

**Comment by mbloms** [comment]
> The equal sign in `depname=version` specifies an exact version restriction. If the `gazebo` package does not really require version `6` of `sdformat`, then it should specify `sdformat>=6`. Or if it requires `sdformat-6` instead, then the PKGBUILD should reflect that.

The problem here is not the syntax in the PKGBUILD. The problem is that there is no package in the official repositories that provide `sdformat=6`. If `sdformat-6` which provides `sdformat=6` would've been in an repository (not AUR), then this would've worked fine.

The problem is that trizen doesn't search the AUR for other packages that `provides` the dependency. The confusion is very understandable. It's the same issue as #118.

Unfortunately the AUR RPC still does not support searching by the `provides` field. And last time someone talked about it on the mailing list was about 1 year ago.
https://lists.archlinux.org/pipermail/aur-dev/2019-February/004637.html
