### ISSUE TITLE
Unattended upgrades

### ISSUE THREAD

**Issue by lUNuXl** [trizen/trizen#242]
Hello,

I have a problem with upgrading aur packages, the build times are taking forever and trizen is asking for sudo password after it finished build of __**EVERY SINGLE ONE**__ of the 30+ packges.

Which means that I have to input my sudo password __**30+ times**__ and wait for __**each**__ of the packages to finish building. Which means that I just don't bother with it and live with packages that are never updated, it's not worth this much of a hassle.

Is there any way to just tell this package manager to build everything and ask just once for the password upon installation?
Or better - just give it a password for sudo and let it do everything in the background.

**Comment by trizen** [comment]
Hi,

For security reasons, by default, `trizen` executes `sudo --remove-timestamp` before executing `makepkg`. To change this behavior, set in the configuration file:

```perl
  sudo_remove_timestamp      => 0,
```

In order to make `trizen` ask for the `sudo` password only once (executing `sudo -v` in the background every 180 seconds), set in the config file:

```perl
  sudo_autorepeat            => 1,
```

Additionally, to execute `sudo -v` at the very beginning, also set:

```perl
  sudo_autorepeat_at_runtime => 1,
```

The config options are also available as command-line arguments:

```console
trizen --sudo_remove_timestamp=0 --sudo_autorepeat=1 --sudo_autorepeat_at_runtime=1 -S <packages>
```
